### ISSUE TITLE
1.6.4 client cannot use sign.

### ISSUE THREAD

**Issue by qiuDar** [ProtocolSupport/ProtocolSupportBungee#22]
1.6.4 client cannot use sign.

18:13:01 [SEVERE] [b3m322] <-> DownstreamBridge <-> [lobby] - encountered exception
io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Unknown packet id: 133
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:391)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:823)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:339)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:255)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Unknown packet id: 133
    at protocolsupport.protocol.transformer.v_1_6.reader.NonDefinedPacketReader.readPacket(NonDefinedPacketReader.java:89)
    at protocolsupport.protocol.transformer.v_1_4_1_5_1_6_core.reader.PacketReader.readPacket(PacketReader.java:92)
    at protocolsupport.protocol.transformer.v_1_4_1_5_1_6_core.PacketDecoder.decode(PacketDecoder.java:35)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:360)
    ... 12 more
18:13:01 [INFO] [b3m322] disconnected with: §fDecoderException : java.lang.IllegalArgumentException: Unknown packet id: 133 @ io.netty.handler.codec.ByteToMessageDecoder:391
18:13:01 [INFO] [b3m322] disconnected with: §f[Proxy] Lost connection to server.

**Comment by qiuDar** [comment]
My version is used.
The server version is 1.8.8
http://build.true-games.org/job/ProtocolSupport/388/
http://ci.md-5.net/job/BungeeCord/1119/
http://build.true-games.org/job/ProtocolSupportBungee/13/

**Comment by Zilacon** [comment]
I am having a similar issue using 1.10.2 Spigot with HexagonBungee.
https://github.com/ProtocolSupport/ProtocolSupport/issues/283
