### ISSUE TITLE
java.lang.UnsupportedOperationException: direct buffer

### ISSUE THREAD

**Issue by oloflarsson** [ProtocolSupport/ProtocolSupportBungee#24]
Running ProtocolSupportBungee build number 23 (http://build.true-games.org/job/ProtocolSupportBungee/21/).

I occasionally see this error in my Bungee console:

```
06:15:54 [INFO] [IriCrescent] <-> ServerConnector [s8] has connected
06:15:54 [INFO] [IriCrescent] <-> ServerConnector [s1] has connected
06:15:54 [INFO] [IriCrescent] <-> ServerConnector [s8] has disconnected
06:15:54 [INFO] [/37.187.63.146:55743] <-> InitialHandler has connected
06:16:17 [INFO] [/121.6.104.57:57513] <-> InitialHandler has connected
06:16:18 [WARNING] [/121.6.104.57:57513] <-> InitialHandler - IOException: syscall:read(...)() failed: Connection reset by peer
06:16:23 [INFO] [/37.187.160.171:40944] <-> InitialHandler has connected
06:16:42 [SEVERE] [/158.69.241.133:47549] <-> InitialHandler - encountered exception
io.netty.handler.codec.DecoderException: java.lang.UnsupportedOperationException: direct buffer
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at protocolsupport.protocol.listeners.initial.InitialPacketDecoder.setProtocol(InitialPacketDecoder.java:110)
	at protocolsupport.protocol.listeners.initial.Minecraft152PingResponseTask.run(Minecraft152PingResponseTask.java:19)
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:408)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.UnsupportedOperationException: direct buffer
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.array(UnpooledUnsafeDirectByteBuf.java:198)
	at protocolsupport.protocol.transformer.v_1_4_1_5_1_6_core.reader.PacketReader.readDefinedPacket(PacketReader.java:115)
	at protocolsupport.protocol.transformer.v_1_4_1_5_1_6_core.reader.PacketReader.readPacket(PacketReader.java:83)
	at protocolsupport.protocol.transformer.v_1_4_1_5_1_6_core.PacketDecoder.decode(PacketDecoder.java:35)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
	... 17 more
```

**Comment by Shevchik** [comment]
Will fix it when i have time.

**Comment by Shevchik** [comment]
Should be fixed now
