### ISSUE TITLE
[1.5.2] Error

### ISSUE THREAD

**Issue by Luuzzi** [ProtocolSupport/ProtocolSupportBungee#27]
http://pastebin.com/HrD4UFHg

**Comment by MrPowerGamerBR** [comment]
@Luuzzi same error here 😢 

```

20:11:35 [SEVERE] [/189.18.91.164:57443] <-> InitialHandler - encountered exception
io.netty.handler.codec.DecoderException: java.lang.UnsupportedOperationException: not a replayable operation
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
    at protocolsupport.protocol.listeners.initial.InitialPacketDecoder.setProtocol(InitialPacketDecoder.java:111)
    at protocolsupport.protocol.listeners.initial.Minecraft152PingResponseTask.run(Minecraft152PingResponseTask.java:19)
    at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
    at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:306)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.UnsupportedOperationException: not a replayable operation
    at protocolsupport.utils.ReplayingDecoderBuffer.reject(ReplayingDecoderBuffer.java:945)
    at protocolsupport.utils.ReplayingDecoderBuffer.discardSomeReadBytes(ReplayingDecoderBuffer.java:905)
    at protocolsupport.protocol.transformer.v_1_4_1_5_1_6_core.PacketDecoder.decode(PacketDecoder.java:50)
    at protocolsupport.protocol.transformer.v_1_4_1_5_1_6_core.PacketDecoder.decode(PacketDecoder.java:17)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
    ... 17 more
```
