### ISSUE TITLE
1.5.2 & 1.6.4 clients cannot login.

### ISSUE THREAD

**Issue by Zilacon** [ProtocolSupport/ProtocolSupportBungee#28]
I get "End of Stream" or "Failed to connect" when trying to connect using 1.6.4, 1.5.2 and it wont let me connect at all with 1.4.7 (not really important).

Any idea how to fix this? Heres some screenshots. The top one is a direct link to the vanilla spigot 1.10.2 server and the bottom 2 are bungeecord forced hosts.

![screenshot_9](https://cloud.githubusercontent.com/assets/3002248/19234113/6c02e942-8e9e-11e6-9c3b-79f2c89fa3c1.png)
![screenshot_10](https://cloud.githubusercontent.com/assets/3002248/19234111/6bfe61ec-8e9e-11e6-8280-29a2754c13fa.png)
![screenshot_11](https://cloud.githubusercontent.com/assets/3002248/19234112/6bfef166-8e9e-11e6-9470-09b167c7392f.png)

EDIT: Tested the vanilla server alone (without bungee) and it worked up to 1.5.2 correctly. However with ProtocolSupportBungee i get this:

````
io.netty.handler.codec.DecoderException: java.lang.UnsupportedOperationException: direct buffer
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at protocolsupport.protocol.listeners.initial.InitialPacketDecoder.setProtocol(InitialPacketDecoder.java:111)
	at protocolsupport.protocol.listeners.initial.InitialPacketDecoder.channelRead(InitialPacketDecoder.java:90)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:972)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:386)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:302)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.UnsupportedOperationException: direct buffer
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.array(UnpooledUnsafeDirectByteBuf.java:203)
	at protocolsupport.protocol.transformer.v_1_4_1_5_1_6_core.PacketDataSerializer.readString(PacketDataSerializer.java:12)
	at protocolsupport.protocol.transformer.v_1_4_1_5_1_6_core.packets.HandshakePacket.read(HandshakePacket.java:31)
	at protocolsupport.protocol.transformer.v_1_4_1_5_1_6_core.reader.PacketReader.readDefinedPacket(PacketReader.java:111)
	at protocolsupport.protocol.transformer.v_1_4_1_5_1_6_core.reader.PacketReader.readPacket(PacketReader.java:42)
	at protocolsupport.protocol.transformer.v_1_4_1_5_1_6_core.PacketDecoder.decode(PacketDecoder.java:41)
	at protocolsupport.protocol.transformer.v_1_4_1_5_1_6_core.PacketDecoder.decode(PacketDecoder.java:17)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
	... 22 more
````

I am using the latest version of HexagonBungee

**Comment by Zilacon** [comment]
Any update on this?

**Comment by Shevchik** [comment]
Will work on it tomorrow

**Comment by MrPowerGamerBR** [comment]
Same error here, if @Shevchik needs, here is my stack trace:
```
io.netty.handler.codec.DecoderException: java.lang.UnsupportedOperationException: direct buffer
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
    at protocolsupport.protocol.listeners.initial.InitialPacketDecoder.setProtocol(InitialPacketDecoder.java:111)
    at protocolsupport.protocol.listeners.initial.InitialPacketDecoder.channelRead(InitialPacketDecoder.java:90)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:972)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:386)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:302)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.UnsupportedOperationException: direct buffer
    at io.netty.buffer.UnpooledUnsafeDirectByteBuf.array(UnpooledUnsafeDirectByteBuf.java:203)
    at protocolsupport.protocol.transformer.v_1_4_1_5_1_6_core.PacketDataSerializer.readString(PacketDataSerializer.java:12)
    at protocolsupport.protocol.transformer.v_1_4_1_5_1_6_core.packets.HandshakePacket.read(HandshakePacket.java:31)
    at protocolsupport.protocol.transformer.v_1_4_1_5_1_6_core.reader.PacketReader.readDefinedPacket(PacketReader.java:111)
    at protocolsupport.protocol.transformer.v_1_4_1_5_1_6_core.reader.PacketReader.readPacket(PacketReader.java:42)
    at protocolsupport.protocol.transformer.v_1_4_1_5_1_6_core.PacketDecoder.decode(PacketDecoder.java:41)
    at protocolsupport.protocol.transformer.v_1_4_1_5_1_6_core.PacketDecoder.decode(PacketDecoder.java:17)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
    ... 22 more
```

**Comment by Shevchik** [comment]
Should be fixed now.

**Comment by Zilacon** [comment]
I now get this:
````
[B#347]  2016-10-14 20:58:00 [INFO] [STDERR] java.util.zip.ZipException: Not in GZIP format
[B#347]  2016-10-14 20:58:00 [INFO] [STDERR] 	at java.util.zip.GZIPInputStream.readHeader(Unknown Source)
[B#347]  2016-10-14 20:58:00 [INFO] [STDERR] 	at java.util.zip.GZIPInputStream.<init>(Unknown Source)
[B#347]  2016-10-14 20:58:00 [INFO] [STDERR] 	at java.util.zip.GZIPInputStream.<init>(Unknown Source)
[B#347]  2016-10-14 20:58:00 [INFO] [STDERR] 	at net.minecraft.nbt.CompressedStreamTools.func_74792_a(CompressedStreamTools.java:62)
[B#347]  2016-10-14 20:58:00 [INFO] [STDERR] 	at net.minecraft.network.packet.Packet.func_73283_d(Packet.java:349)
[B#347]  2016-10-14 20:58:00 [INFO] [STDERR] 	at net.minecraft.network.packet.Packet.func_73276_c(Packet.java:303)
[B#347]  2016-10-14 20:58:00 [INFO] [STDERR] 	at net.minecraft.network.packet.Packet104WindowItems.func_73267_a(SourceFile:30)
[B#347]  2016-10-14 20:58:00 [INFO] [STDERR] 	at net.minecraft.network.packet.Packet.func_73272_a(Packet.java:166)
[B#347]  2016-10-14 20:58:00 [INFO] [STDERR] 	at net.minecraft.network.TcpConnection.func_74447_i(TcpConnection.java:325)
[B#347]  2016-10-14 20:58:00 [INFO] [STDERR] 	at net.minecraft.network.TcpConnection.func_74450_c(TcpConnection.java:549)
[B#347]  2016-10-14 20:58:00 [INFO] [STDERR] 	at net.minecraft.network.TcpReaderThread.run(SourceFile:94)
````

![screenshot_17](https://cloud.githubusercontent.com/assets/3002248/19407242/ac5100be-9250-11e6-972c-fa863760a2cf.png)

**Comment by Shevchik** [comment]
Try now

**Comment by Zilacon** [comment]
Alright so it let me login to the hub with 1.6.4 so i linked my 1.6.4 servers up to hexagon bungee, joined the hub on 1.6.4 Agrarian Skies and did /server as and it gives me this:
````
[B#347]  2016-10-14 21:14:50 [INFO] [Minecraft-Client] [CHAT] Exception Connecting:NativeIoException : syscall:read(...)() failed: Connection reset by peer @ io.netty.channel.unix.FileDescriptor:-1
````
Any idea what this is?

**Comment by Shevchik** [comment]
No idea, stopped working with modded servers long time ago.

**Comment by Zilacon** [comment]
I just remembered i did not place ProtocolSupport plugin into my AgrarianSkies server so i did that now it crashed on start up :(

**Comment by Shevchik** [comment]
ProtocolSupport only works on latest server version.

**Comment by Zilacon** [comment]
So if ProtocolSupport adds 1.5.2/1.6.4 support to Bungee why does it prevent connections to 1.5.2/1.6.4?
Im confused...

**Comment by Shevchik** [comment]
Because ProtocolSupport uses different login sequence than normal 1.5.2/1.6. ProtocolSupportBungee most likely relies on it.

**Comment by Zilacon** [comment]
So theres no way to login to a 1.6.4 server from a bungee server with protocolsupport on it?

**Comment by Shevchik** [comment]
No idea, as i already said i never used ProtooclSupportBungee myself.

**Comment by Zilacon** [comment]
Could i hire you to make this work if it is possible? If so how much would you charge?
