### ISSUE TITLE
ProtocolSupportBungee doesn't support mc 1.5.2

### ISSUE THREAD

**Issue by Singlerr** [ProtocolSupport/ProtocolSupportBungee#44]
I added it to the plugins folder in BungeeCord(1.12.2) and started the server,but i can't connect to the bungeecord.
Even my minecraft(1.5.2) couldn't reach the server.

**Comment by Icey-girl** [comment]
You need hexacord

**Comment by Singlerr** [comment]
Still not working.
 1?? 02, 2018 3:37:21 ???? io.netty.channel.ChannelInitializer exceptionCaught
???: Failed to initialize a channel. Closing: [id: 0xdc6295d5, L:/127.0.0.1:25577 - R:/127.0.0.1:50007]
java.lang.NoSuchMethodError: net.md_5.bungee.connection.InitialHandler.<init>(Lnet/md_5/bungee/api/ProxyServer;Lnet/md_5/bungee/api/config/ListenerInfo;)V
	at protocolsupport.protocol.CheckedInitialHandler.<init>(CheckedInitialHandler.java:12)
	at protocolsupport.injector.NettyInjector$ProxyChannelInitializer.initChannel(NettyInjector.java:31)
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113)
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:606)
	at io.netty.channel.DefaultChannelPipeline.access$000(DefaultChannelPipeline.java:46)
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1412)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1131)
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:656)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:510)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:423)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:482)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Unknown Source)

**Comment by Shevchik** [comment]
You are using a version that is from spigot, which doesn't work for a long time already.
You need the latest dev build.

**Comment by Singlerr** [comment]
Then what version i  exactly use?

**Comment by Singlerr** [comment]
and bungeecord or hexacord...

**Comment by Singlerr** [comment]
Oh,I solved this error.Thank you for answering this issue.

**Comment by Singlerr** [comment]
I used the latest version of PSBungee and Hexacord from Jenkins.But the motd of my server doesn't show when i refresh the list of server.
