### ISSUE TITLE
Plugin works with: 1.5.2, 1.7.x,1.8.x but when I try to join with a 1.6.x client, minecraft crashes with this problem:

### ISSUE THREAD

**Issue by drizzerx** [ProtocolSupport/ProtocolSupportBungee#7]
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 16/10/15 2:54
Description: Deserializing Message

java.lang.ClassCastException: com.google.gson.JsonPrimitive cannot be cast to com.google.gson.JsonObject
    at cx.a(SourceFile:14)
    at cx.deserialize(SourceFile:10)
    at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
    at com.google.gson.Gson.fromJson(Gson.java:795)
    at com.google.gson.Gson.fromJson(Gson.java:761)
    at com.google.gson.Gson.fromJson(Gson.java:710)
    at com.google.gson.Gson.fromJson(Gson.java:682)
    at cv.c(SourceFile:220)
    at bcw.a(SourceFile:522)
    at dm.a(SourceFile:49)
    at co.b(SourceFile:354)
    at bcw.e(SourceFile:98)
    at bcy.c(SourceFile:71)
    at atv.k(SourceFile:1173)
    at atv.S(SourceFile:663)
    at atv.d(SourceFile:619)
    at net.minecraft.client.main.Main.main(SourceFile:101)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at cx.a(SourceFile:14)
    at cx.deserialize(SourceFile:10)
    at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
    at com.google.gson.Gson.fromJson(Gson.java:795)
    at com.google.gson.Gson.fromJson(Gson.java:761)
    at com.google.gson.Gson.fromJson(Gson.java:710)
    at com.google.gson.Gson.fromJson(Gson.java:682)

-- Serialized Message --
Details:
    JSON string: §f§f§cHas entrado al servidor: lobby
Stacktrace:
    at cv.c(SourceFile:220)
    at bcw.a(SourceFile:522)
    at dm.a(SourceFile:49)
    at co.b(SourceFile:354)
    at bcw.e(SourceFile:98)
    at bcy.c(SourceFile:71)

-- Affected screen --
Details:
    Screen name: bcy
Stacktrace:
    at atv.k(SourceFile:1173)
    at atv.S(SourceFile:663)
    at atv.d(SourceFile:619)
    at net.minecraft.client.main.Main.main(SourceFile:101)

-- System Details --
Details:
    Minecraft Version: 1.6.4
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_60, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 220025168 bytes (209 MB) / 255066112 bytes (243 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: No suspicious classes found.
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    Launched Version: 1.6.4
    LWJGL: 2.9.0
    OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.5.0 NVIDIA 358.50, NVIDIA Corporation
    Is Modded: Probably not. Jar signature remains and client brand is untouched.
    Type: Client (map_client.txt)
    Resource Pack: Default
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: ~~ERROR~~ NullPointerException: null

**Comment by James137137** [comment]
yeah I'm getting same same error http://pastebin.com/0vjpt4hy

**Comment by Shevchik** [comment]
BungeeCord chat messages are not remapped yet, so yea any plugin that sends messages from bungee will crash clients.

**Comment by James137137** [comment]
so which classes would we remove?
