### ISSUE TITLE
Newer versions can't reach the server

### ISSUE THREAD

**Issue by Artuto** [ProtocolSupport/ProtocolSupportBungee#73]
I was testing the 18w49a snapshot today and I clicked the multiplayer option in the main menu, I didn't expect to join a server, but to see if something changed there.

I saw many networks and small servers with their normal MOTD and player count displaying, however, mine was just shown as offline. Then I opened my Bungee Console and I saw this;

```java
[12:07:01 ERROR]: [/IP:50298] <-> InitialHandler - encountered exception
java.lang.NullPointerException: null
at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.setProtocol(InitialPacketDecoder.java:208) ~[?:?]
at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.decodeRaw(InitialPacketDecoder.java:137) ~[?:?]
at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.decode(InitialPacketDecoder.java:93) ~[?:?]
at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.channelRead0(InitialPacketDecoder.java:73) ~[?:?]
at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.channelRead0(InitialPacketDecoder.java:34) ~[?:?]
at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:433) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:330) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

I know no one will be able to join using a snapshot, however, this indeed isn't a proper behaviour and I hope it'll be fixed.

**Comment by Artuto** [comment]
Any update on this? Its getting a lot annoying when players refresh their list on the latest snapshots and my console gets the stacktrace printed three or four times
