### ISSUE TITLE
[1.5.2] End of stream when connecting on 1.9.4 server

### ISSUE THREAD

**Issue by De4dm4sterBR** [ProtocolSupport/ProtocolSupportBungee#83]
Hi,

I've tested several builds of ProtocolSupportBungee, ProtocolSupport, but i'm not able to solve this problem.
I'm using the latest build of Hexacord, and a 1.9.4 Paper Server with ProtocolSupport, and the latest build of ProtocolSupportBungee.
I'm able to see the MOTD on list, but, when i try to connect, it just stays on "Loading" and then "End of Stream". No errors are thrown on console.

Connecting from 1.8+ versions works fine.

How can i debug it?
Can you help me?

**Comment by De4dm4sterBR** [comment]
Enabled debug on PS, heres the stack:

[00:06:37 INFO]: Enabled debug
[00:06:40 INFO]: /127.0.0.1:3778 connected with protocol version MINECRAFT_1_5_2
[00:06:45 WARN]: java.lang.IndexOutOfBoundsException
[00:06:45 WARN]:        at io.netty.buffer.EmptyByteBuf.readByte(EmptyByteBuf.java:440)
[00:06:45 WARN]:        at protocolsupport.utils.netty.ChannelUtils.readVarInt(ChannelUtils.java:43)
[00:06:45 WARN]:        at protocolsupport.protocol.core.initial.ProtocolUtils.readNettyHandshake(ProtocolUtils.java:34)
[00:06:45 WARN]:        at protocolsupport.protocol.core.initial.InitialPacketDecoder.attemptDecodeNettyHandshake(InitialPacketDecoder.java:177)
[00:06:45 WARN]:        at protocolsupport.protocol.core.initial.InitialPacketDecoder.decode(InitialPacketDecoder.java:140)
[00:06:45 WARN]:        at protocolsupport.protocol.core.initial.InitialPacketDecoder.channelRead0(InitialPacketDecoder.java:92)
[00:06:45 WARN]:        at protocolsupport.protocol.core.initial.InitialPacketDecoder.channelRead0(InitialPacketDecoder.java:27)
[00:06:45 WARN]:        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
[00:06:45 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[00:06:45 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[00:06:45 WARN]:        at protocolsupport.protocol.core.timeout.SimpleReadTimeoutHandler.channelRead(SimpleReadTimeoutHandler.java:40)
[00:06:45 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[00:06:45 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[00:06:45 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
[00:06:45 WARN]:        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
[00:06:45 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
[00:06:45 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
[00:06:45 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
[00:06:45 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
[00:06:45 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[00:06:45 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by astei** [comment]
1.9.4 is ancient and isn't supported with ProtocolSupport anymore
