### ISSUE TITLE
No souch method.

### ISSUE THREAD

**Issue by TemaFlux** [ProtocolSupport/ProtocolSupportBungee#85]
[07:43:49 WARN]: Exception encountered when loading plugin: ProtocolSupportBungee
java.lang.NoSuchMethodError: net.md_5.bungee.api.ProxyConfig.isDisableEntityMetadataRewrite()Z
        at protocolsupport.ProtocolSupport.onEnable(ProtocolSupport.java:24) ~[ProtocolSupportBungee.jar:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:250) [core.jar:git:BungeeCord-Bootstrap:1.16-R0.3-SNAPSHOT:47585d7:unknown]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:309) [core.jar:git:BungeeCord-Bootstrap:1.16-R0.3-SNAPSHOT:47585d7:unknown]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:43) [core.jar:git:BungeeCord-Bootstrap:1.16-R0.3-SNAPSHOT:47585d7:unknown]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) [core.jar:git:BungeeCord-Bootstrap:1.16-R0.3-SNAPSHOT:47585d7:unknown]

**Comment by Shevchik** [comment]
PSB only supports Travertine.
