### ISSUE TITLE
1.5x & 1.6x Client Can't Login "End Stream"

### ISSUE THREAD

**Issue by JamerBadal** [ProtocolSupport/ProtocolSupportBungee#86]
My Server is 1.8-1.5x
1.8 WORK FINE AND THE 1.7
BUT IF USE 1.6X or 1.5x vversion and connect to bungeecord servers
i will get kicked the reason "END STREAM"
I KNOW THIS IS OLD. Also i need it please help.
-Sorry for bad english 
Log:
io.netty.handler.codec.EncoderException: java.lang.NullPointerException
at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:633)
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:691)
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:626)
at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:944)
at io.netty.channel.AbstractChannel.write(AbstractChannel.java:239)
at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:49)
at net.md_5.bungee.UserConnection$1.sendPacket(UserConnection.java:138)
at net.md_5.bungee.tab.ServerUnique.onServerChange(ServerUnique.java:77)
at protocolsupport.protocol.transformer.v_1_5_v1_6_shared.handlers.ServerConnectHandler.handle(ServerConnectHandler.java:162)
at net.md_5.bungee.protocol.packet.Login.handle(Login.java:60)
at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:76)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
at java.lang.Thread.run(Thread.java:823)
Caused by: java.lang.NullPointerException
at protocolsupport.protocol.transformer.v_1_5_v1_6_shared.PacketDataSerializer.writeString(PacketDataSerializer.java:16)
at protocolsupport.protocol.transformer.v_1_5_v1_6_shared.packets.PlayerListItemPacket.write(PlayerListItemPacket.java:44)
at protocolsupport.protocol.transformer.v_1_5_v1_6_shared.PacketEncoder.encodePackets(PacketEncoder.java:43)
at protocolsupport.protocol.transformer.v_1_5_v1_6_shared.PacketEncoder.encode(PacketEncoder.java:33)
at protocolsupport.protocol.transformer.v_1_5_v1_6_shared.PacketEncoder.encode(PacketEncoder.java:14)
at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)

**Comment by Shevchik** [comment]
The link to to dev builds is literally in the readme.

**Comment by JamerBadal** [comment]
> The link to dev builds is literally in the readme.

can you send me a link?

**Comment by JamerBadal** [comment]
i want 1.8-1.5x server
