### ISSUE TITLE
 Exception encountered when loading plugin: ProtocolSupportBungee

### ISSUE THREAD

**Issue by tnht** [ProtocolSupport/ProtocolSupportBungee#88]
[WARNING] Exception encountered when loading plugin: ProtocolSupportBungee
java.lang.NoSuchMethodError: net.md_5.bungee.api.ProxyConfig.isDisableEntityMetadataRewrite()Z
	at protocolsupport.ProtocolSupport.onEnable(ProtocolSupport.java:24)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:250)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:285)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

When i'm starting bungeecord.

**Comment by Shevchik** [comment]
Only compatible with travertine.
