### ISSUE TITLE
Failed to initialize a channel.

### ISSUE THREAD

**Issue by codergautam** [ProtocolSupport/ProtocolSupportBungee#89]
[13:55:36 WARN] [io.netty.channel.ChannelInitializer]: Failed to initialize a channel. Closing: [id: 0x1524f5de, L:/127.0.0.1:25565 - R:/127.89.3.251:57173]
java.lang.NoSuchMethodError: net.md_5.bungee.connection.InitialHandler.<init>(Lnet/md_5/bungee/api/ProxyServer;Lnet/md_5/bungee/api/config/ListenerInfo;)V
        at protocolsupport.protocol.CheckedInitialHandler.<init>(CheckedInitialHandler.java:12) ~[?:?]
        at protocolsupport.injector.NettyInjector$ProxyChannelInitializer.initChannel(NettyInjector.java:31) ~[?:?]
        at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129) ~[travertine-1.16-179.jar:git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:fffc15e:179]
        at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112) ~[travertine-1.16-179.jar:git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:fffc15e:179]
        at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:938) ~[travertine-1.16-179.jar:git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:fffc15e:179]
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609) ~[travertine-1.16-179.jar:git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:fffc15e:179]
        at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46) ~[travertine-1.16-179.jar:git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:fffc15e:179]
        at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463) ~[travertine-1.16-179.jar:git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:fffc15e:179]
        at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115) ~[travertine-1.16-179.jar:git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:fffc15e:179]
        at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650) ~[travertine-1.16-179.jar:git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:fffc15e:179]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:502) ~[travertine-1.16-179.jar:git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:fffc15e:179]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:417) ~[travertine-1.16-179.jar:git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:fffc15e:179]
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:474) ~[travertine-1.16-179.jar:git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:fffc15e:179]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[travertine-1.16-179.jar:git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:fffc15e:179]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[travertine-1.16-179.jar:git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:fffc15e:179]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[travertine-1.16-179.jar:git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:fffc15e:179]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[travertine-1.16-179.jar:git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:fffc15e:179]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[travertine-1.16-179.jar:git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:fffc15e:179]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by codergautam** [comment]
Used dev builds(readme) solved
