### ISSUE TITLE
The server you were previously on went down, you have been connected to a fallback server

### ISSUE THREAD

**Issue by codergautam** [ProtocolSupport/ProtocolSupportBungee#90]
[13:59:41 ERROR]: [/127.89.3.251:57346|CoderPvP] <-> DownstreamBridge <-> [bedwars] - encountered exception
java.lang.IndexOutOfBoundsException: readerIndex(10) + length(8) exceeds writerIndex(17): PooledUnsafeDirectByteBuf(ridx: 10, widx: 17, cap: 17)
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1478) ~[travertine-1.16-179.jar:git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:fffc15e:179]
        at io.netty.buffer.AbstractByteBuf.readLong(AbstractByteBuf.java:837) ~[travertine-1.16-179.jar:git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:fffc15e:179]
        at net.md_5.bungee.protocol.DefinedPacket.readUUID(DefinedPacket.java:238) ~[travertine-1.16-179.jar:git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:fffc15e:179]
        at net.md_5.bungee.entitymap.EntityMap_1_16_2.rewriteClientbound(EntityMap_1_16_2.java:122) ~[travertine-1.16-179.jar:git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:fffc15e:179]
        at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:148) ~[travertine-1.16-179.jar:git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:fffc15e:179]
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:113) ~[travertine-1.16-179.jar:git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:fffc15e:179]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[travertine-1.16-179.jar:git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:fffc15e:179]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[travertine-1.16-179.jar:git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:fffc15e:179]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[travertine-1.16-179.jar:git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:fffc15e:179]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93) ~[travertine-1.16-179.jar:git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:fffc15e:179]
        at protocolsupport.protocol.pipeline.common.LogicHandler.channelRead(LogicHandler.java:27) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[travertine-1.16-179.jar:git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:fffc15e:179]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[travertine-1.16-179.jar:git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:fffc15e:179]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[travertine-1.16-179.jar:git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:fffc15e:179]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[travertine-1.16-179.jar:git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:fffc15e:179]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[travertine-1.16-179.jar:git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:fffc15e:179]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[travertine-1.16-179.jar:git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:fffc15e:179]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[travertine-1.16-179.jar:git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:fffc15e:179]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[travertine-1.16-179.jar:git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:fffc15e:179]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311) ~[travertine-1.16-179.jar:git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:fffc15e:179]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432) ~[travertine-1.16-179.jar:git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:fffc15e:179]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[travertine-1.16-179.jar:git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:fffc15e:179]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[travertine-1.16-179.jar:git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:fffc15e:179]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[travertine-1.16-179.jar:git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:fffc15e:179]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[travertine-1.16-179.jar:git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:fffc15e:179]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[travertine-1.16-179.jar:git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:fffc15e:179]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[travertine-1.16-179.jar:git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:fffc15e:179]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[travertine-1.16-179.jar:git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:fffc15e:179]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[travertine-1.16-179.jar:git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:fffc15e:179]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[travertine-1.16-179.jar:git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:fffc15e:179]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[travertine-1.16-179.jar:git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:fffc15e:179]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[travertine-1.16-179.jar:git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:fffc15e:179]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[travertine-1.16-179.jar:git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:fffc15e:179]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[travertine-1.16-179.jar:git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:fffc15e:179]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) ~[travertine-1.16-179.jar:git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:fffc15e:179]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) ~[travertine-1.16-179.jar:git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:fffc15e:179]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) ~[travertine-1.16-179.jar:git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:fffc15e:179]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[travertine-1.16-179.jar:git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:fffc15e:179]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[travertine-1.16-179.jar:git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:fffc15e:179]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[travertine-1.16-179.jar:git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:fffc15e:179]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[13:59:41 INFO]: [CoderPvP] disconnected with: The server you were previously on went down, you have been connected to a fallback server

**Comment by Shevchik** [comment]
Entity rewriting must be disabled.
